apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::033367561754:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1K0MN6W37UPE7
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::033367561754:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-01T04:40:00Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1645"
  uid: 5a06ac06-e441-45b1-ad25-8a206df6bf97
